# ConfigMap for common environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MONGO_URI: "mongodb+srv://akashkumarsenthilkumar_db_user:mTnLH54vQAmmNjir@yelp.wvxiqvo.mongodb.net/?retryWrites=true&w=majority&appName=yelp"
  DB_NAME: "yelp_db"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
  JWT_SECRET: "akash_yelp_lab_secret_key_2024_!@#"
  S3_BUCKET_NAME: "yelp-restaurant-photos-akash-lab2"
  AWS_REGION: "us-east-1"
