apiVersion: apps/v1
kind: Deployment
metadata:
  name: owner-api
  labels:
    app: owner-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owner-api
  template:
    metadata:
      labels:
        app: owner-api
    spec:
      containers:
        - name: owner-api
          image: 256056996949.dkr.ecr.us-east-2.amazonaws.com/yelp-owner-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8004
          envFrom:
          - configMapRef:
              name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: owner-api
spec:
  selector:
    app: owner-api
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
  type: ClusterIP